webdriver {
    driver = chrome
    chrome {
        driver_path = "C:/Users/Lenovo/Downloads/Nueva carpeta (18)/chromedriver-win64/chromedriver.exe"
    }
}

serenity {
    project.name = "Contact List Tests"
}